import { makeLesson, question } from '../lessonFactory'

const hermesSource = 'Hermes 的安裝、模型供應商、工具與安全設定會持續更新；本階段教穩定概念，實際命令與選項請以目前官方文件及本機版本為準。'

export const phaseThreeLessons = [
  makeLesson({
    id: 'lesson-17', phase: 3, lessonNumber: 17,
    title: 'Hermes Agent 是什麼', subtitle: '從視覺化流程走向可操作的 Agent Runtime',
    description: '把已學會的 Coze Workflow 放回更大的 Agent 系統中，理解 Hermes 的定位、優勢與邊界。',
    objectives: ['說出 Coze 與 Hermes 的層級差異', '判斷任務適合固定 Workflow 或可操作 Agent', '知道模型、Agent Runtime 與工具不是同一件事'],
    prerequisites: ['完成 Phase 2 Coze 起步', '理解 Agent、Tool 與 Workflow'],
    concepts: [
      { term: 'Hermes Agent', chinese: 'Hermes 智能體', plain: '能使用工具、記憶與 Skills，在多個工作階段持續完成任務的 Agent 系統。', definition: '由 Nous Research 維護、可在 CLI、桌面程式或訊息 Gateway 執行的自主 Agent；它會依模型判斷選擇工具與後續步驟。', why: '讓你從「搭一條流程」進一步理解「讓 Agent 在環境中完成工作」。', example: 'Hermes 讀取專案檔案、執行測試、整理結果，再等待你確認是否提交。', commonConfusion: 'Hermes 不是另一個大模型；它需要連接模型 Provider 才能運作。' },
      { term: 'Agent Runtime', chinese: '智能體運行環境', plain: '負責讓模型、工具、記憶、權限與工作階段一起運作的程式層。', definition: '承接模型輸出並管理工具呼叫、工作階段狀態、權限與結果回傳的執行環境。', why: '同一個模型放進不同 Runtime，能做的事、風險與記憶方式可能不同。', example: 'Claude 是模型；Hermes 是可以讓 Claude 使用終端機與瀏覽器的 Runtime。', commonConfusion: 'Coze 與 Hermes 都能建立 Agent，但它們承擔的產品層級與執行邊界不同。' },
    ],
    metaphor: 'Coze 像透明的自動化工作台：你把 Start、LLM、End 接好；Hermes 像一位坐在工作台前的操作員，能讀說明、選工具、執行步驟並回報證據。',
    technicalExplanation: ['Coze 的 Workflow 先設計節點與資料流，再發布給使用者或 API 呼叫。', 'Hermes 以 Agent Runtime 管理模型、工具、Skills、Memory 與工作階段。', '模型只負責推理與產生訊息；能否讀檔、執行命令或開瀏覽器取決於 Runtime 的工具與權限。', '任務固定且要稽核時先用 Workflow；下一步依證據改變時才考慮 Agent。'],
    diagram: ['模型 Provider', 'Hermes Runtime', 'Tools／Skills／Memory', '工作環境', '結果與人工確認'],
    caseStudy: { title: '詢價資料整理助手', label: '模擬案例', description: 'Coze 固定執行輸入 → 分類 → 草稿；Hermes 則可在你批准後讀取本機資料、整理缺漏並提出下一步。' },
    steps: ['把一個工作拆成固定步驟與不確定步驟。', '標出哪些資料需要讀取、哪些動作可能改變外部世界。', '固定部分保留 Workflow；需要根據證據調整的部分才交給 Agent。', '最後寫出人工確認點與停止條件。'],
    exercise: { prompt: '比較「每天固定產出詢價草稿」與「找出一份資料夾中最可能的缺漏文件」：哪一個先用 Coze Workflow，哪一個可能使用 Hermes？', success: ['說出固定與不確定的差異', '沒有把工具能力等同自動授權', '補上人工確認或只讀邊界'], hint: '先問下一步能不能在開始前完整寫死。', answer: '每天固定產出詢價草稿適合先用 Coze Workflow；從資料夾找缺漏文件可能需要 Hermes 的檔案與搜尋工具，但先設定只讀範圍並由人確認後續動作。' },
    quiz: [question('q17', 'single', '哪個說法最準確？', ['Hermes 是一個比 Claude 更大的模型', 'Coze 與 Hermes 都是完全相同的 Workflow 編輯器', 'Coze 偏向建置與發布流程；Hermes 偏向讓 Agent 在工具環境中持續工作'], 2, 'Coze 與 Hermes 可以一起使用，但主要解決的層級不同；Hermes 本身不是模型。', '比較產品在系統中的位置，而不是比較名稱。')],
    commonErrors: [{ mistake: '把 Hermes 當成模型名稱', cause: '只看到聊天介面', fix: '分開記住模型、Runtime、Tool 與資料來源' }, { mistake: '所有任務都改成自主 Agent', cause: '把彈性誤當優勢', fix: '固定流程先用 Workflow，高風險動作保留人工批准' }],
    summary: ['Coze 偏向把 Agent／Workflow 建置與發布出來。', 'Hermes 偏向讓 Agent 在工具、記憶與工作環境中持續完成任務。', '模型、Runtime、Tool 與權限要分開設計。'], nextLesson: '下一課：Hermes Desktop 與模型 Provider', verification: '已確認', sourceNote: hermesSource,
  }),
  makeLesson({
    id: 'lesson-18', phase: 3, lessonNumber: 18,
    title: 'Hermes Desktop 與模型 Provider', subtitle: '先讓 Agent 安全地連上模型',
    description: '理解 Hermes 的 CLI／Desktop 入口與 Provider 設定，不把模型、帳號與工具權限混為一談。',
    objectives: ['說出 Provider 的角色', '知道 Hermes 可切換雲端與自架模型端點', '建立不暴露秘密的設定檢查習慣'],
    prerequisites: ['完成 Hermes Agent 是什麼'],
    concepts: [
      { term: 'Provider', chinese: '模型供應商', plain: '提供模型推理服務與連線方式的一方。', definition: '負責接收提示與工具回合、回傳模型結果的服務或自架端點；Hermes 可透過設定選擇 Provider。', why: '換 Provider 不等於換 Agent 設計；它主要改變模型來源、費用、速度與資料路徑。', example: '同一個 Hermes 工作流程可以改用 Anthropic、OpenAI-compatible endpoint 或自架服務。', commonConfusion: 'Provider、模型名稱與 Hermes Desktop 都是不同層級。' },
      { term: 'Custom Endpoint', chinese: '自訂端點', plain: '提供 OpenAI 相容 API 的自架或第三方服務網址。', definition: '只要服務提供相容的聊天完成介面，就可在 Hermes 設定 base URL、模型名稱與必要金鑰。', why: '讓你能在雲端模型、自架推理服務或本機模型之間選擇。', example: '把內網的相容 API 指到 Hermes 的 custom provider。', commonConfusion: '能連上端點不代表模型一定支援足夠的上下文或工具呼叫。' },
    ],
    metaphor: 'Provider 像外聘大腦供應商；Hermes 是工作室與操作規則。你可以換大腦，但工作室的工具、檔案與安全門仍要另外管理。',
    technicalExplanation: ['Hermes 官方文件提供 Desktop、CLI 與 Gateway 等入口。', 'Provider 設定決定模型從哪裡來；`hermes model` 是設定或切換 Provider 的入口。', '官方目前列出雲端 Provider，也支援 OpenAI-compatible custom endpoint；實際可用模型依帳號、版本與端點能力而異。', 'API 金鑰與 OAuth token 應放在 Hermes 的秘密設定位置，不要貼進 Prompt、課程截圖或 Git。'],
    diagram: ['Hermes Desktop／CLI', 'Provider 設定', '模型 API 或自架端點', '模型回應', '再交給 Tools／Runtime'],
    caseStudy: { title: '本機學習助理', label: '模擬案例', description: '學習者先選可用的模型 Provider，再確認端點、上下文長度、費用與資料是否會離開本機；不在課程中代填真實金鑰。' },
    steps: ['先記錄你要解決的任務與資料敏感度。', '查看 Hermes 官方 Provider 清單與目前版本限制。', '用 `hermes model` 或 Desktop 設定選擇 Provider，不把秘密貼到聊天。', '用一個無敏感資料的短問題測試連線，再記錄模型、日期與結果。'],
    exercise: { prompt: '為你的 Hermes 學習環境寫一張 Provider 檢查卡。', success: ['有 Provider 與模型名稱', '有端點／資料路徑判斷', '沒有把金鑰寫進筆記'], hint: '先記錄可驗證的設定，不要記錄秘密本身。', answer: 'Provider：目前選用的官方或自架服務；模型：實際模型名稱；端點：官方雲端或內網 URL；上下文：是否符合多步工具任務；秘密：只存在安全設定檔，不寫入課程筆記。' },
    quiz: [question('q18', 'true-false', '只要 Hermes 能啟動，就代表目前模型一定支援所有工具與長上下文任務。', ['正確', '錯誤'], 1, '啟動只證明部分設定可用；模型上下文、工具呼叫、Provider 限制與權限仍要分開驗證。', '啟動成功和能力驗證不是同一件事。')],
    commonErrors: [{ mistake: '把 API 金鑰貼在 Prompt 或 Git', cause: '把設定當一般文字', fix: '用秘密設定檔並在提交前檢查' }, { mistake: '只測「你好」', cause: '沒有驗證實際任務能力', fix: '用無敏感資料測一個最小工具回合與輸出格式' }],
    summary: ['Provider 決定模型服務與資料路徑。', 'Hermes、Provider、模型與工具權限要分層驗證。', '課程只記錄設定事實，不保存秘密。'], nextLesson: '下一課：Tools 與 Skills', verification: '版本敏感', sourceNote: hermesSource,
  }),
  makeLesson({
    id: 'lesson-19', phase: 3, lessonNumber: 19,
    title: 'Tools 與 Skills', subtitle: '把「能做什麼」和「怎麼做」分開',
    description: '理解 Hermes 的 Toolset 與 Skill 如何互補，並用最小權限設計第一個可重複任務。',
    objectives: ['區分 Tool、Toolset 與 Skill', '為任務選最少必要能力', '檢查 Skill 來源與需要的工具'],
    prerequisites: ['完成 Hermes Desktop 與模型 Provider', '理解 Phase 1 的 Tool 與 Skill'],
    concepts: [
      { term: 'Toolset', chinese: '工具組', plain: '把一組相關工具一起開啟或關閉的能力集合。', definition: 'Hermes 用來管理工具可見範圍的命名集合，例如 web、file、terminal、browser、memory 或 delegation。', why: '用工具組可以先限制 Agent 能看見與呼叫的能力，降低誤用與除錯範圍。', example: '整理公開資料只開 web；修改專案才另外評估 file 與 terminal。', commonConfusion: '開啟 Toolset 只是提供能力，不代表每一次都應該允許 Agent 使用。' },
      { term: 'Hermes Skill', chinese: 'Hermes 技能文件', plain: '讓 Agent 在需要時載入的任務方法、步驟與邊界。', definition: 'Hermes 使用的可載入程序文件，可保存任務指引、命令、範例與工具需求，並可依 agentskills.io 方向分享。', why: '把「怎麼做」從每次聊天中抽出來，讓同一類工作更一致。', example: '把 RFQ 整理的欄位規則、來源核對與待確認格式寫成 Skill。', commonConfusion: 'Skill 是程序與知識，不等於能直接讀檔或寄信的 Tool。' },
    ],
    metaphor: 'Tool 是工作室裡的螺絲起子；Toolset 是你拿到的工具箱；Skill 是教你怎麼完成一種工作的作業手冊。',
    technicalExplanation: ['Hermes 官方 Toolsets 將 web、file、terminal、browser、memory 等工具分組管理。', 'Skill 以按需載入的程序文件保存方法，能使用現有工具，但不會自動取得超出設定的權限。', '先從只讀、單一任務、最少 Toolset 開始，再依證據增加能力。', 'Skill 來源、內容、命令與外部資料流都要檢查；不要只因名稱好聽就安裝。'],
    diagram: ['任務目標', 'Skill：方法與規則', 'Toolset：可用能力範圍', 'Tool：實際執行', '輸出與證據'],
    caseStudy: { title: '只讀 RFQ 整理 Skill', label: '模擬案例', description: 'Skill 指定先擷取規格、標記待確認，再輸出摘要；只開啟讀取檔案與文字整理能力，不開啟刪除、寄信或付款能力。' },
    steps: ['寫下任務的輸入、輸出與禁止事項。', '只選完成任務所需的 Toolset。', '把可重複的方法寫成短 Skill，標出需要的工具。', '以正常、缺資料與衝突資料測試，留下結果和未授權動作。'],
    exercise: { prompt: '設計一個「整理產品詢價」的 Hermes Skill，並列出最小 Toolset。', success: ['Skill 有清楚輸入與輸出', '工具組只讀且最小', '未知資料標記待確認'], hint: '先排除寄信、刪除與付款；本題只做整理。', answer: 'Skill：讀取使用者提供的詢價文字或檔案，整理產品、數量、交期、缺漏與待確認；Toolset：file（只讀）與必要的文字處理，關閉 terminal、messaging 與任何付款工具。' },
    quiz: [question('q19', 'single', '哪個設計最符合最小權限？', ['整理 RFQ 時開啟所有工具，讓 Agent 自己選', '只開啟必要的只讀工具，寄信與刪除能力保持關閉', '先開付款工具，之後再觀察有沒有用到'], 1, '工具能力越少越容易預測與稽核；對外或破壞性動作應另設批准。', '先問任務是否真的需要該權限。')],
    commonErrors: [{ mistake: '把 Skill 當成 Tool', cause: '只看到最後的動作', fix: 'Skill 寫方法；Tool 才執行外部能力' }, { mistake: '為方便開啟 all', cause: '沒有先定義任務邊界', fix: '從最小 Toolset 開始並逐一記錄新增理由' }],
    summary: ['Tool 是能力；Toolset 是能力集合；Skill 是方法。', '最小權限比「什麼都能做」更適合學習與驗證。', '每個 Skill 都要有來源、輸入、輸出與禁止事項。'], nextLesson: '下一課：Memory 與工作階段', verification: '版本敏感', sourceNote: hermesSource,
  }),
  makeLesson({
    id: 'lesson-20', phase: 3, lessonNumber: 20,
    title: 'Memory 與工作階段', subtitle: '讓 Agent 記得有用的事，不是把一切都保存',
    description: '區分當前工作階段、跨工作階段記憶與專案檔案，建立可檢查的記憶邊界。',
    objectives: ['區分 Session、Memory 與檔案', '判斷哪些資訊值得跨工作階段保存', '為敏感資料設定不保存規則'],
    prerequisites: ['完成 Tools 與 Skills', '理解 Phase 1 的 Memory 與 Knowledge Base'],
    concepts: [
      { term: 'Session', chinese: '工作階段', plain: '一次連續的對話與工具執行脈絡。', definition: '包含目前對話、工具結果與暫時狀態的工作範圍；結束後不應假設所有內容都會永久保留。', why: '先知道資訊活多久，才不會把暫時上下文誤當長期記憶。', example: '本次除錯的錯誤輸出只在 Session 中使用。', commonConfusion: '聊天紀錄、Session State、長期 Memory 與檔案不是同一件事。' },
      { term: 'Persistent Memory', chinese: '持久記憶', plain: '跨多次工作階段保留、可再次取用的精簡資訊。', definition: '由 Hermes 管理、可跨 Session 召回的使用者偏好、環境事實或已確認工作脈絡；應受到範圍與審核控制。', why: '讓重複任務不用每次重新說明，但也避免錯誤或秘密長期擴散。', example: '使用者偏好繁體中文；不是把整份客戶名單永久寫進 Memory。', commonConfusion: 'Memory 不是 Knowledge Base，也不是把所有對話全文無限保存。' },
    ],
    metaphor: 'Session 像今天桌上的便條；Persistent Memory 像經過整理後放進檔案櫃的少量索引；原始文件仍應放在可管理的資料夾。',
    technicalExplanation: ['先判斷資訊是本次暫時狀態、可重建的專案檔案，還是值得跨 Session 保存的穩定事實。', '持久記憶應短、準確、可撤回，避免把秘密、一次性猜測或完整敏感資料寫入。', 'Hermes 也有 Session 搜尋與工作階段資料；查到舊內容仍要重新確認是否適用。', '記憶能提高連續性，但不會自動使舊資訊正確或符合最新版本。'],
    diagram: ['本次輸入', 'Session 暫時狀態', '判斷是否值得保存', '精簡 Persistent Memory', '下次取回後重新核對'],
    caseStudy: { title: '學習環境記憶', label: '模擬案例', description: '保存「使用繁體中文、專案放在某個已核准資料夾」等穩定偏好；不保存 API 金鑰、客戶個資與未驗證推測。' },
    steps: ['列出任務中會出現的資訊。', '把每一項標成 Session、專案檔案或候選 Memory。', '對候選 Memory 寫保存理由、來源與撤回方式。', '下一次取回時重新核對日期、來源與是否仍適用。'],
    exercise: { prompt: '以下資訊哪些可作為學習助理的長期 Memory：偏好繁體中文、今天的 API 金鑰、目前正在修的錯誤訊息、已確認的專案資料夾？', success: ['排除秘密', '區分暫時錯誤與穩定環境事實', '說出取回後仍需核對'], hint: '長期保存的門檻是穩定、有用、低敏感且可驗證。', answer: '偏好繁體中文與已確認的專案資料夾可作為候選 Memory；API 金鑰不應寫入 Memory；今天的錯誤訊息先留在 Session 或專案紀錄，除非整理成可重用的已確認規則。' },
    quiz: [question('q20', 'true-false', '把完整客戶名單與 API 金鑰寫進 Persistent Memory，能讓 Hermes 更聰明，所以是好做法。', ['正確', '錯誤'], 1, 'Memory 應精簡且受邊界控制；秘密與大份敏感資料不應因方便而長期保存。', '有用不等於可以永久保存。')],
    commonErrors: [{ mistake: '把所有聊天都當長期記憶', cause: '沒有區分生命週期', fix: '先標記 Session、檔案與候選 Memory' }, { mistake: '相信取回的舊資料一定正確', cause: '把記憶當即時來源', fix: '重新核對來源、日期與目前狀態' }],
    summary: ['Session 是目前工作脈絡；Memory 是經過選擇的跨工作階段資訊。', '秘密、完整敏感資料與未驗證猜測不應寫進長期記憶。', '取回記憶後仍要檢查日期與適用性。'], nextLesson: '下一課：安全執行與最小權限實作', verification: '已確認', sourceNote: hermesSource,
  }),
  makeLesson({
    id: 'lesson-21', phase: 3, lessonNumber: 21,
    title: '安全執行與最小權限實作', subtitle: '能動手做之前，先知道何時必須停下來',
    description: '把 Hermes 的命令批准、隔離、人工確認與證據記錄整合成一個安全的最小練習。',
    objectives: ['辨認需要人工批准的動作', '知道 local、container 與遠端後端的邊界', '完成一次可回溯的安全測試記錄'],
    prerequisites: ['完成 Memory 與工作階段', '理解 Tool 權限與人工審核'],
    concepts: [
      { term: 'Command Approval', chinese: '命令批准', plain: 'Agent 執行高風險命令前，要求人先確認。', definition: 'Hermes 對符合危險模式的命令提供 manual、smart 或 off 等批准策略；批准不等於作業系統隔離。', why: '避免模型一次誤刪、覆寫或對外操作造成不可逆結果。', example: '刪除大量檔案、修改系統設定或對外發送內容前停下來。', commonConfusion: '看到批准提示不代表整個 Agent 已被沙盒完全隔離。' },
      { term: 'Isolation', chinese: '隔離', plain: '把 Agent 的命令與檔案能力限制在指定環境。', definition: '透過 Docker、SSH、雲端沙盒或其他作業系統邊界限制 Agent 可接觸的檔案、程序與網路；隔離強度取決於實際後端設定。', why: '當 Agent 需要執行不可信程式或處理敏感資料時，單靠 Prompt 與批准不夠。', example: '先在測試資料夾或容器中跑讀取與測試，不直接碰公司正式資料。', commonConfusion: 'Tool allowlist 與 Prompt 規則是控制；真正的 containment 仍要看 OS／容器邊界。' },
    ],
    metaphor: '批准提示像門口保全；隔離環境像圍牆。保全可能攔住某些動作，但沒有圍牆時，不能假設整個園區都安全。',
    technicalExplanation: ['先把資料夾、工具、命令與對外通道列成白名單。', '危險命令預設要人工批准；不要為了方便直接關閉批准或使用 yolo 模式。', '真正需要執行程式或修改檔案時，優先使用可回復的測試目錄、容器或遠端隔離後端。', '每次測試記錄輸入、模型、工具、批准、輸出與是否改動檔案，讓結果可回溯。'],
    diagram: ['任務需求', '最小工具與資料夾', 'Agent 提議動作', '批准／拒絕', '隔離環境執行', '記錄證據'],
    caseStudy: { title: '只讀專案檢查', label: '模擬案例', description: 'Hermes 只能讀取測試專案並執行不改檔的檢查；任何寫入、刪除、提交或對外傳送都必須停止並由人確認。' },
    steps: ['建立一個不含秘密的測試資料夾。', '只開啟必要的 file／terminal 能力，先採只讀任務。', '執行列出檔案或讀取 README 等低風險測試。', '若出現寫入、刪除、網路或對外行動，拒絕並記錄原因。', '把結果整理成「預期 → 實際 → 證據 → 下一步」四欄。'],
    exercise: { prompt: '設計一個「檢查專案是否缺少測試」的安全 Hermes 任務。', success: ['測試資料夾不含秘密', '只讀或可回復的權限', '寫入與對外動作有人批准', '保留執行證據'], hint: '先讓 Agent 只讀檔案與執行測試，不要讓它直接修檔或提交。', answer: '把專案複製到測試資料夾，開啟必要的 file／terminal；要求 Hermes 只讀 README、列出測試檔並執行不改檔的測試。若它提議修改、刪除、commit 或發送結果，先停止並由人批准；最後保存命令、輸出與錯誤證據。' },
    quiz: [question('q21', 'scenario', 'Hermes 建議刪除一批檔案來「清理專案」，你應先做什麼？', ['直接讓它執行，因為它已經分析過', '關閉所有批准提示，讓流程順利完成', '停止並檢查目標、備份／隔離與人工批准，再決定是否執行'], 2, '刪除是高風險且可能不可逆的動作；先確認範圍與復原方式，不把 Agent 的建議當授權。', '把「建議」和「授權執行」分開。')],
    commonErrors: [{ mistake: '把批准提示當完整沙盒', cause: '混淆應用層控制與 OS 隔離', fix: '需要時使用容器、遠端或測試目錄' }, { mistake: '直接在正式資料上測試', cause: '想快速看到結果', fix: '先複製、脫敏、只讀並保留證據' }],
    summary: ['批准控制高風險動作；隔離提供更深的環境邊界。', '先只讀、最小權限、可回復，再逐步增加能力。', 'Hermes 的能力越大，越需要人確認與可回溯證據。'], nextLesson: 'Phase 3 完成：進入 Workflow 思維', verification: '已確認', sourceNote: hermesSource,
  }),
]
