import { makeLesson, question, stableConcept } from '../lessonFactory'

export const phaseOneLessons = [
  makeLesson({
    id: 'lesson-01', phase: 1, lessonNumber: 1,
    title: 'LLM 是什麼', subtitle: '先認識會產生文字的 AI 大腦',
    description: '理解 LLM 能做什麼、不能做什麼，以及為什麼流暢不等於正確。',
    objectives: ['用白話解釋 LLM', '分辨生成文字與查詢事實', '辨認需要查證的回答'],
    prerequisites: ['不需要程式設計基礎'],
    concepts: [{ term: 'LLM', chinese: '大型語言模型', plain: '讀過大量文字後，根據上下文預測下一段文字的系統。', definition: '以大量文字資料訓練、依輸入產生文字序列的機器學習模型。', why: '它是許多聊天機器人與 Agent 的語言能力來源。', example: '把一段會議紀錄整理成三個重點。', commonConfusion: 'LLM 不是資料庫，也不保證記得的是最新事實。' }],
    metaphor: 'LLM 像一位讀過很多資料、很會接話的助理；他能快速起草，但交出的數字與來源仍要核對。',
    technicalExplanation: ['輸入文字會被模型轉成可計算的表示。', '模型根據前文估計接下來最可能出現的內容。', '它產生的是合理語句，不是自動完成事實查證。'],
    diagram: ['你的問題', 'LLM 根據上下文預測', '產生回答', '人工／工具查證'],
    caseStudy: { title: '會議摘要助手', label: '模擬案例', description: '輸入會議逐字稿，LLM 可以整理決策與待辦；人名、日期與金額仍需對照原文。' },
    steps: ['找一段 100 字內的公開說明文字。', '請 AI 用三點摘要，不加入原文沒有的資訊。', '逐句把摘要與原文對照，標出新增或遺漏。'],
    exercise: { prompt: '用一句話向家人解釋：為什麼 LLM 說得很順，答案仍可能錯？', success: ['提到它是在產生文字', '提到流暢不代表已查證'], hint: '想想「很會接話」和「真的查過資料」是否相同。', answer: 'LLM 是根據上下文產生最可能的文字，不是每次都去查可靠資料，所以說得流暢仍可能出錯。' },
    quiz: [question('q01', 'true-false', 'LLM 產生很自然的文字，就代表內容已經查證。', ['正確', '錯誤'], 1, 'LLM 的工作是產生文字；是否正確需要來源、工具或人工核對。', '把「生成」和「查證」分開想。')],
    commonErrors: [{ mistake: '把模型記憶當成即時資料', cause: '回答語氣很肯定', fix: '要求來源與日期，再用可靠來源核對' }, { mistake: '一次要求太多任務', cause: '沒有拆解目標', fix: '先摘要，再查缺漏，最後改寫' }],
    summary: ['LLM 擅長理解與產生文字。', '流暢不等於正確或最新。', '重要事實需要工具、來源或人工驗證。'],
    nextLesson: '下一課：Prompt 是什麼', verification: stableConcept,
  }),
  makeLesson({
    id: 'lesson-02', phase: 1, lessonNumber: 2,
    title: 'Prompt 是什麼', subtitle: '把模糊想法變成可理解的任務',
    description: '學會用目標、背景、限制與輸出格式說清楚需求。',
    objectives: ['辨認 Prompt 的四個部分', '把模糊要求改成可執行指示', '避免把不存在的資料交給模型猜'], prerequisites: ['完成 Lesson 01'],
    concepts: [{ term: 'Prompt', chinese: '提示詞', plain: '你交給 AI 的任務說明。', definition: '用來引導模型行為與輸出內容的輸入指令及上下文。', why: '說清楚目標和邊界，才能得到更可用的結果。', example: '把這封詢價信整理成產品、數量、交期三欄；缺少就寫待確認。', commonConfusion: 'Prompt 不是咒語，也不能保證模型知道你沒有提供的事實。' }],
    metaphor: 'Prompt 像交辦工作：只說「幫我弄一下」很難做好；說清楚目的、材料、限制與交付格式，助理才知道怎麼開始。',
    technicalExplanation: ['目標說要完成什麼。', '背景提供完成任務所需資料。', '限制指出不能做什麼或如何處理未知。', '格式讓結果能直接檢查與使用。'],
    diagram: ['目標', '+ 背景', '+ 限制', '+ 輸出格式', '可檢查的 Prompt'],
    caseStudy: { title: '詢價信整理', label: '模擬案例', description: '要求 AI 只根據來信填欄位，缺少的規格一律標記「待確認」，不自行補全。' },
    steps: ['寫下一個模糊要求：「幫我分析這家公司」。', '補上分析目的與已知材料。', '加入不得虛構及輸出三個段落的限制。'],
    exercise: { prompt: '把「幫我整理新聞」改成包含目標、背景、限制、格式的 Prompt。', success: ['四個部分齊全', '要求保留來源與日期', '未知內容不猜測'], hint: '先決定整理給誰看、要看哪幾欄。', answer: '請根據我貼上的新聞文字，為主管整理事件、影響、來源日期三欄；只使用原文，無法確認就寫待確認，以表格輸出。' },
    quiz: [question('q02', 'scenario', '哪個 Prompt 最容易檢查？', ['幫我寫好一點', '根據附件整理 3 個決策與負責人；缺少就寫待確認', '自由發揮'], 1, '它說明資料來源、輸出內容與未知資訊的處理方式。', '找得到目標、邊界和格式的選項。')],
    commonErrors: [{ mistake: '只加很多形容詞', cause: '沒有定義成功結果', fix: '補上可檢查的欄位與限制' }, { mistake: '要求模型補齊缺失事實', cause: '把推測當資料', fix: '明訂未知寫待確認' }],
    summary: ['好 Prompt 讓任務可理解也可檢查。', '目標、背景、限制、格式比神奇關鍵字重要。'], nextLesson: '下一課：Agent 是什麼', verification: stableConcept,
  }),
  makeLesson({
    id: 'lesson-03', phase: 1, lessonNumber: 3,
    title: 'Agent 是什麼', subtitle: '讓 AI 根據目標選擇下一步',
    description: '理解 Agent 如何觀察、決定、使用工具，再根據結果繼續。',
    objectives: ['說出 Agent 與單次聊天的差異', '辨認 Agent 的目標、決策與工具', '知道高風險動作需要人工批准'], prerequisites: ['完成 LLM 與 Prompt'],
    concepts: [{ term: 'Agent', chinese: '智能體', plain: '能根據目標與目前情況，決定下一步行動的 AI 系統。', definition: '以模型作為決策元件，能觀察狀態、選擇行動、呼叫工具並迭代的系統。', why: '當任務步驟不能完全事先固定時，需要依結果調整。', example: '研究助理先找資料，發現來源不足後再換查詢方向。', commonConfusion: 'Agent 不是完全自由；它仍需要權限、停止條件與人工邊界。' }],
    metaphor: 'Agent 像拿到目標的研究助理：他會看現況、選方法、查資料、檢查結果，再決定是否繼續。',
    technicalExplanation: ['目標定義要完成什麼。', '狀態保存目前已知資訊。', '模型選擇下一個行動。', '工具執行行動並把結果送回。'],
    diagram: ['目標', '觀察目前狀態', '決定下一步', '使用 Tool', '檢查結果 ↺'],
    caseStudy: { title: '競品研究 Agent', label: '模擬案例', description: 'Agent 先查官方網站；來源不足時改查官方文件，最後交給 Reviewer 檢查引用。' },
    steps: ['選一個開放式研究目標。', '列出 Agent 可用與不可用的工具。', '寫下何時停止、何時要求人工確認。'],
    exercise: { prompt: '為「研究三家供應商」寫出 Agent 的目標、兩個工具與一個人工批准點。', success: ['目標可驗證', '工具和目標相關', '批准點在對外或高風險行動前'], hint: '搜尋與整理可以自動；最後選供應商是否該由 AI 決定？', answer: '目標：依官方規格與交期整理三家比較；工具：官方網站搜尋、表格整理；批准點：送出詢價或做採購決策前由人確認。' },
    quiz: [question('q03', 'single', '哪個情境最需要 Agent 的動態決策？', ['每天 08:00 固定寄同一份報表', '研究問題並依找到的證據調整查詢方向', '把檔案複製到固定資料夾'], 1, '研究步驟會隨證據改變，適合由 Agent 選擇下一步。', '找「下一步無法完全預先寫死」的情境。')],
    commonErrors: [{ mistake: '給 Agent 過大權限', cause: '把自動化等同自主決策', fix: '採最小權限與人工批准' }, { mistake: '沒有停止條件', cause: '只寫目標沒有完成標準', fix: '定義來源數、品質與最大步數' }],
    summary: ['Agent 依狀態選下一步。', '工具、權限、停止條件共同決定安全性。'], nextLesson: '下一課：Tool 是什麼', verification: stableConcept,
  }),
  makeLesson({
    id: 'lesson-04', phase: 1, lessonNumber: 4,
    title: 'Tool 是什麼', subtitle: '讓 AI 不只說話，還能取得或處理外部資訊',
    description: '理解 Tool 的輸入、執行與輸出，以及最小權限。',
    objectives: ['區分模型能力與 Tool 能力', '辨認 Tool 的輸入輸出', '為高風險 Tool 加上人工確認'], prerequisites: ['完成 Agent'],
    concepts: [{ term: 'Tool', chinese: '工具', plain: 'AI 可以呼叫的一項外部能力。', definition: '以明確輸入、輸出和權限暴露給 Agent 或 Workflow 的可執行功能。', why: '模型本身不能可靠存取即時網站、資料庫或檔案。', example: '查天氣、讀取產品 CSV、建立草稿。', commonConfusion: '「可以呼叫寄信 Tool」不等於應該允許自動寄出。' }],
    metaphor: 'LLM 像大腦，Tool 像手上的計算機、電話或資料櫃；大腦要先選對工具，工具才會回傳結果。',
    technicalExplanation: ['Tool 有名稱與用途。', '輸入需要清楚欄位。', '執行後回傳結果或錯誤。', '權限決定它能讀、寫或對外動作到什麼程度。'],
    diagram: ['Agent 決定', 'Tool 輸入', '外部系統執行', '結果／錯誤', 'Agent 繼續'],
    caseStudy: { title: '庫存查詢 Tool', label: '模擬案例', description: 'Agent 只讀取 SKU 與數量；修改庫存不是這個 Tool 的權限。' },
    steps: ['挑一個「查詢型」工具。', '列出必要輸入與回傳欄位。', '寫出一項不允許的動作。'],
    exercise: { prompt: '設計一個「查產品規格」Tool 的輸入、輸出與權限。', success: ['輸入最少且明確', '輸出可驗證', '只讀邊界清楚'], hint: '查規格不需要修改或刪除產品。', answer: '輸入：產品型號；輸出：型號、規格、來源文件日期；權限：只能讀取已核准產品資料，不可新增、修改或刪除。' },
    quiz: [question('q04', 'true-false', '只要 Agent 能呼叫寄信 Tool，就應該讓它自動寄出任何內容。', ['正確', '錯誤'], 1, '對外寄送會影響真實世界，通常需要權限限制、草稿預覽與人工批准。', '能力與授權是兩件事。')],
    commonErrors: [{ mistake: '工具描述含糊', cause: 'Agent 不知道何時使用', fix: '寫清用途、必要輸入與禁止事項' }, { mistake: '讀取任務給寫入權限', cause: '為方便而過度授權', fix: '使用最小權限' }],
    summary: ['Tool 把外部能力提供給 Agent 或 Workflow。', '輸入、輸出、錯誤與權限都要明確。'], nextLesson: '下一課：Workflow 是什麼', verification: stableConcept,
  }),
  makeLesson({
    id: 'lesson-05', phase: 1, lessonNumber: 5,
    title: 'Workflow 是什麼', subtitle: '把固定工作變成可檢查的流程',
    description: '理解 Workflow 的步驟、順序、條件與可重現性。', objectives: ['用 SOP 解釋 Workflow', '把任務拆成輸入與步驟', '找出人工批准位置'], prerequisites: ['完成 Tool'],
    concepts: [{ term: 'Workflow', chinese: '工作流', plain: '按照預先設計的步驟處理工作的流程。', definition: '由節點與連線組成、按規則傳遞資料並執行任務的可重現流程。', why: '固定、重複、需要追蹤的工作適合用 Workflow。', example: '每天抓資料 → 摘要 → 寫入表格 → 寄出。', commonConfusion: 'Workflow 可以包含 AI 節點，但不代表整條流程都是 Agent。' }],
    metaphor: 'Workflow 就像公司的 SOP：收到詢價後，先查資料、再寫草稿、交主管確認，最後才寄出。',
    technicalExplanation: ['輸入啟動流程。', '每個節點完成一項工作。', '連線決定資料如何往下走。', '條件與錯誤路徑處理不同情況。'],
    diagram: ['收到詢價', '查產品', '生成草稿', '人工批准', '寄出'],
    caseStudy: { title: '每日新聞摘要', label: '模擬案例', description: '每天固定時間執行相同步驟；若沒有新聞，走「無資料」路徑而不是硬產生摘要。' },
    steps: ['寫出一項每天重複的工作。', '拆成 4 至 6 個步驟。', '標出輸入、輸出、錯誤路徑與人工批准。'],
    exercise: { prompt: '把「收到詢價後回覆客戶」拆成五步 Workflow。', success: ['順序合理', 'AI 與資料查詢分開', '寄出前有人工確認'], hint: '先取得資料，再讓 AI 起草；不要讓 AI 自己決定商業承諾。', answer: '收到詢價 → 擷取需求 → 查核產品資料 → AI 生成草稿 → 主管確認後寄出。' },
    quiz: [question('q05', 'scenario', '每天 08:00 抓新聞、摘要、寄 Email，最主要適合什麼？', ['Agent', 'Workflow', 'Database'], 1, '步驟與時間固定，適合可重現的 Workflow；其中摘要步驟可以使用 LLM。', '看步驟是否預先固定。')],
    commonErrors: [{ mistake: '把整個流程塞進一個 LLM', cause: '沒有拆節點', fix: '把查詢、生成、批准分開' }, { mistake: '沒有無資料路徑', cause: '只設計成功情境', fix: '加入錯誤與空資料處理' }],
    summary: ['Workflow 適合固定、重複、可追蹤的工作。', 'AI 可以是其中一個節點。'], nextLesson: '下一課：Agent vs Workflow', verification: stableConcept,
  }),
  makeLesson({
    id: 'lesson-06', phase: 1, lessonNumber: 6,
    title: 'Agent vs Workflow', subtitle: '先問步驟固定嗎，再決定用什麼',
    description: '用不確定性、風險與可追蹤性選擇 Agent、Workflow 或混合設計。', objectives: ['用固定程度做初步判斷', '辨認混合架構', '避免為了炫技使用 Agent'], prerequisites: ['完成 Agent 與 Workflow'],
    concepts: [{ term: 'Hybrid', chinese: '混合式設計', plain: '固定主流程裡，只在需要判斷的地方使用 Agent。', definition: '以 Workflow 約束流程，並在特定節點引入模型或 Agent 決策的架構。', why: '同時保留可控性與彈性。', example: '固定收件與批准，中間由 Agent 判斷產品類型。', commonConfusion: '混合式不是把所有技術都放進去，而是各自放在最適合的位置。' }],
    metaphor: '火車照固定軌道運行像 Workflow；探索未知地形的嚮導像 Agent。真實系統常是火車把你送到區域，再由嚮導處理不確定問題。',
    technicalExplanation: ['步驟固定、結果可預期：優先 Workflow。', '下一步依證據改變：考慮 Agent。', '高風險與需要稽核：用 Workflow 包住 Agent。'],
    diagram: ['固定觸發', 'Workflow 主線', 'Agent 判斷支線', '人工批准', '可追蹤輸出'],
    caseStudy: { title: '詢價混合系統', label: '模擬案例', description: '收件、查資料與寄送是固定步驟；產品分類模糊時交給 Agent，低信心則轉人工。' },
    steps: ['寫下任務的固定步驟。', '圈出需要依內容判斷的步驟。', '把高風險動作移到人工批准後。'],
    exercise: { prompt: '判斷「市場研究報告」哪些部分用 Workflow、哪些用 Agent。', success: ['固定排程與輸出用 Workflow', '研究方向調整用 Agent', '來源與發布有人審核'], hint: '不要強迫整個系統只選一種。', answer: 'Workflow 負責排程、收集欄位、合併報告與送審；Agent 根據證據調整搜尋與分析方向；Reviewer 或人員確認來源後發布。' },
    quiz: [question('q06', 'single', '哪個判斷順序最合理？', ['先選最新工具，再想需求', '先看步驟是否固定、風險與證據需求，再選架構', '所有任務都用 Agent'], 1, '架構應由任務的不確定性與風險決定，不由工具熱度決定。', '先需求，後工具。')],
    commonErrors: [{ mistake: '所有 AI 任務都用 Agent', cause: '把 Agent 當成比較高級', fix: '固定任務優先 Workflow' }, { mistake: 'Agent 直接執行高風險動作', cause: '缺少邊界', fix: '用流程、權限與人工批准包住' }],
    summary: ['固定流程優先 Workflow；動態決策才考慮 Agent。', '混合式設計常是最實用的答案。'], nextLesson: '下一課：Skill 是什麼', verification: stableConcept,
  }),
  makeLesson({
    id: 'lesson-07', phase: 1, lessonNumber: 7,
    title: 'Skill 是什麼', subtitle: '把一種做事方法整理成可重複能力',
    description: '理解 Skill 如何封裝指引、資源與步驟，也知道它不是萬能插件。', objectives: ['用能力模組解釋 Skill', '辨認 Skill 與 Tool 的差異', '知道 Skill 名稱可能依平台不同'], prerequisites: ['完成 Agent 與 Tool'],
    concepts: [{ term: 'Skill', chinese: '技能', plain: '教 AI 用一致方法完成某一類任務的能力包。', definition: '封裝任務指引、流程、範例或可呼叫資源的可重用能力單元；實作依平台而異。', why: '避免每次從零描述同一套做法。', example: '報價需求整理 Skill 規定欄位、缺漏標記與輸出格式。', commonConfusion: 'Skill 描述怎麼做；Tool 是實際執行外部動作的能力。' }],
    metaphor: 'Skill 像員工的作業手冊與訓練；Tool 像他使用的儀器。會操作儀器不等於知道完整作業方法。',
    technicalExplanation: ['Skill 的定義不是所有平台共用的同一標準。', '它通常聚焦特定任務、輸入、方法與產出。', '若 Skill 需要外部資料，仍可能呼叫 Tool。'],
    diagram: ['任務', 'Skill：做事方法', 'Tool：外部能力', '一致產出'],
    caseStudy: { title: 'RFQ 整理 Skill', label: '模擬案例', description: '要求先擷取條件、標記待確認，再產出業務可讀的詢價摘要；只讀資料 Tool 提供產品資訊。' },
    steps: ['選一個你常重複交辦的任務。', '寫出固定原則與輸出格式。', '列出需要的 Tool 與不允許的動作。'],
    exercise: { prompt: '為「會議摘要」Skill 寫出三條規則。', success: ['只用原文', '區分決策與待辦', '缺少負責人時不猜'], hint: '想像每次都要產出相同品質。', answer: '只根據逐字稿；分成決策、待辦、待確認；負責人或期限未提到就標記待確認。' },
    quiz: [question('q07', 'single', 'Skill 與 Tool 最好的區分是？', ['Skill 是方法，Tool 是可執行能力', '兩者永遠完全相同', 'Tool 只是一段 Prompt'], 0, 'Skill 指導怎麼完成一類任務；Tool 對外執行查詢或動作。', '手冊和儀器各自扮演什麼角色？')],
    commonErrors: [{ mistake: '把平台專用 Skill 當通用標準', cause: '不同產品用相同名詞', fix: '標註平台與版本' }, { mistake: 'Skill 內容過大', cause: '想包辦所有任務', fix: '一次只封裝一個清楚能力' }],
    summary: ['Skill 讓做事方法可重複。', '它可以使用 Tool，但兩者角色不同。'], nextLesson: '下一課：Plugin 是什麼', verification: '版本敏感', sourceNote: 'Skill 的產品實作差異很大；需依使用平台官方文件確認。',
  }),
  makeLesson({
    id: 'lesson-08', phase: 1, lessonNumber: 8,
    title: 'Plugin 是什麼', subtitle: '把外部功能接進平台的擴充方式',
    description: '理解 Plugin 的平台依賴、權限與來源風險。', objectives: ['解釋 Plugin 的擴充角色', '比較 Plugin 與 Skill', '安裝前檢查來源與權限'], prerequisites: ['完成 Skill 與 Tool'],
    concepts: [{ term: 'Plugin', chinese: '外掛／插件', plain: '安裝到某個平台、用來增加功能的擴充元件。', definition: '依附特定主程式或平台介面，提供額外功能、整合或工具的軟體模組。', why: '讓平台能連接原本沒有的服務或能力。', example: '在自動化平台加入某個 CRM 的節點。', commonConfusion: 'Plugin 高度依賴平台，不能假設跨產品可直接使用。' }],
    metaphor: 'Plugin 像插在特定機器上的擴充卡；接頭、驅動與權限要相容，不能只看名稱就安裝。',
    technicalExplanation: ['Plugin 由特定平台載入。', '它可能提供 Tool、Node 或介面。', '安裝前要核對開發者、權限與資料流向。'],
    diagram: ['主平台', '安裝 Plugin', '取得新功能', '檢查權限與資料'],
    caseStudy: { title: 'CRM Plugin', label: '模擬案例', description: '先只開啟讀取客戶資料；建立或修改紀錄必須由使用者確認。' },
    steps: ['找到某個 Plugin 的官方來源。', '列出它要求的權限。', '判斷哪些權限超出你的任務。'],
    exercise: { prompt: '安裝一個能讀寫雲端硬碟的 Plugin 前，要檢查哪三件事？', success: ['官方來源', '讀寫範圍', '資料與對外動作'], hint: '能連接不代表該給全部檔案權限。', answer: '核對開發者與官方來源、要求的檔案範圍與讀寫權限、資料會送到哪裡以及刪除／分享是否需人工確認。' },
    quiz: [question('q08', 'true-false', '同名 Plugin 在所有平台一定有相同功能與權限。', ['正確', '錯誤'], 1, 'Plugin 依附平台介面，功能、權限與版本可能不同。', '想想擴充卡是否適用所有機器。')],
    commonErrors: [{ mistake: '從不明來源安裝', cause: '只看功能介紹', fix: '優先官方或可驗證來源' }, { mistake: '不看權限', cause: '一路按允許', fix: '只授權任務需要的最小範圍' }],
    summary: ['Plugin 擴充特定平台。', '來源、相容性與權限比名稱更重要。'], nextLesson: '下一課：Memory 是什麼', verification: '版本敏感', sourceNote: 'Plugin 的名稱、安裝方式與權限由各平台定義。',
  }),
  makeLesson({
    id: 'lesson-09', phase: 1, lessonNumber: 9,
    title: 'Memory 是什麼', subtitle: '保存對後續任務有用的狀態',
    description: '分辨對話內容、短期狀態與持久記錄，避免把記憶當真實來源。', objectives: ['解釋 Memory 的用途', '辨認該保存與不該保存的資訊', '分清 Memory 與 Knowledge Base'], prerequisites: ['完成 Agent'],
    concepts: [{ term: 'Memory', chinese: '記憶', plain: '讓系統在後續步驟記得先前重要資訊。', definition: '為後續推理或流程保存的對話、偏好、任務狀態或摘要。', why: '沒有 Memory，系統可能每一步都重新開始。', example: '記住目前研究問題、已查來源與使用者偏好。', commonConfusion: 'Memory 是過去記錄，不等於經官方驗證的知識。' }],
    metaphor: 'Memory 像工作便條：記住目前做到哪裡；Knowledge Base 更像經整理的資料櫃。便條可能過期或寫錯。',
    technicalExplanation: ['短期 Memory 支援當前對話或任務。', '持久 Memory 跨工作階段保存偏好或摘要。', '敏感資料與過期資訊需要保存期限與刪除機制。'],
    diagram: ['目前輸入', '讀取必要 Memory', '完成一步', '更新任務狀態'],
    caseStudy: { title: '研究任務狀態', label: '模擬案例', description: '記錄已查過的官方來源與待查問題，但不把未驗證結論永久保存為事實。' },
    steps: ['列出任務必須記住的三項狀態。', '刪除不必要的個資或敏感資料。', '為可能過期的內容加日期。'],
    exercise: { prompt: '客服助手哪些資訊適合短期 Memory？', success: ['與當前問題直接相關', '不過度保存敏感資料', '不把推測當事實'], hint: '只保留完成當前服務所需資訊。', answer: '目前問題、已確認的訂單編號、已完成步驟與待辦；密碼、完整付款資料或未確認推測不應保存。' },
    quiz: [question('q09', 'single', '哪個最適合放進任務 Memory？', ['使用者密碼', '已查過的來源清單與下一步', '模型猜測的股價'], 1, '它能避免重複工作並支援下一步；另兩項涉及敏感或不可靠資訊。', '選能支援任務、又不造成不必要風險的。')],
    commonErrors: [{ mistake: '保存所有對話', cause: '以為越多越好', fix: '只留完成任務所需內容' }, { mistake: '沒有時間資訊', cause: '忽略資料會過期', fix: '加日期、來源與更新規則' }],
    summary: ['Memory 保存狀態與上下文。', '它需要最小化、更新與過期規則。'], nextLesson: '下一課：Knowledge Base 是什麼', verification: stableConcept,
  }),
  makeLesson({
    id: 'lesson-10', phase: 1, lessonNumber: 10,
    title: 'Knowledge Base 是什麼', subtitle: '讓回答回到可管理的來源',
    description: '理解 Knowledge Base 的文件來源、檢索與引用，也完成 Phase 1 能力檢核。', objectives: ['區分 Knowledge Base 與 Memory', '知道文件品質決定回答品質', '設計查不到資料時的行為'], prerequisites: ['完成 Memory'],
    concepts: [{ term: 'Knowledge Base', chinese: '知識庫', plain: '整理並提供給系統查找的可信資料集合。', definition: '經收集、整理、索引並可供檢索的文件或結構化知識來源。', why: '讓回答能依組織自己的文件，而不是只靠模型記憶。', example: '產品手冊、FAQ、流程規範與版本記錄。', commonConfusion: '放進知識庫不會自動讓錯誤文件變正確。' }],
    metaphor: 'Knowledge Base 像有目錄與版本標籤的公司資料櫃；系統先找最相關文件，再根據找到的內容回答。',
    technicalExplanation: ['文件先被整理與索引。', '問題進來後先檢索相關片段。', 'LLM 依檢索結果生成回答並附來源。', '找不到時要說不知道或轉人工。'],
    diagram: ['文件與版本', '索引／檢索', '相關片段', 'LLM 回答', '引用來源'],
    caseStudy: { title: '公司產品知識助手', label: '模擬案例', description: '只使用已核准手冊回答；舊版與無日期文件不直接用於對外承諾。' },
    steps: ['挑三份同一主題文件。', '標記來源、日期與版本。', '寫出「查不到」與「來源衝突」時的處理規則。'],
    exercise: { prompt: '設計詢價系統時，哪些部分用 Workflow、Agent、Knowledge Base 與人工審核？', success: ['固定步驟用 Workflow', '模糊分類可用 Agent', '規格來自 Knowledge Base', '承諾前人工確認'], hint: '這是 Phase 1 Mastery Check；從固定與不固定步驟分開。', answer: 'Workflow 負責收件、查詢、草稿、送審與寄出；Agent 處理模糊分類；Knowledge Base 提供有版本的產品規格；主管在價格、交期或對外寄送前確認。' },
    quiz: [question('q10', 'scenario', '知識庫找不到答案時，最合理的行為是？', ['請模型自行補完', '明示查無可靠資料並轉人工或要求補件', '引用沒有日期的舊檔'], 1, '誠實處理缺資料比產生看似完整的答案更安全。', '未知資訊不應由模型猜。')],
    commonErrors: [{ mistake: '文件沒有版本與來源', cause: '只追求快速匯入', fix: '先做來源、日期與責任人治理' }, { mistake: '把檢索結果當絕對正確', cause: '忽略文件品質', fix: '顯示引用並處理衝突' }],
    summary: ['Knowledge Base 提供可管理、可引用的資料來源。', 'Memory 記狀態；Knowledge Base 管知識。', 'Phase 1 的核心是先判斷需求，再選 Agent 或 Workflow。'], nextLesson: '下一站：Phase 2｜Coze 是什麼', verification: stableConcept,
  }),
]
