import { makeLesson, question } from '../lessonFactory'

const cozeSource = 'Coze 介面與按鈕位置更新頻繁；本課只確認穩定概念，實際操作需依目前官方版本確認。'

export const phaseTwoLessons = [
  makeLesson({
    id: 'lesson-11', phase: 2, lessonNumber: 11,
    title: 'Coze 是什麼', subtitle: '先理解平台角色，再開始點擊',
    description: '認識 Coze 作為 AI 應用與 Workflow 建置平台的用途、適用情境與版本邊界。',
    objectives: ['說出 Coze 可以協助的工作', '區分 Agent 與 Workflow 的建置目標', '知道 UI 名稱需要按版本核對'], prerequisites: ['通過 Phase 1 核心概念'],
    concepts: [{ term: 'Coze', chinese: '扣子／Coze 平台', plain: '用視覺方式建立 AI 應用、Agent 與 Workflow 的平台。', definition: '提供模型、Prompt、Workflow、Plugin 等組件來組合 AI 應用的開發平台；可用功能依產品地區與版本而異。', why: '初學者能先看見輸入、節點與輸出之間的關係。', example: '用 Start → LLM → End 建立商業分析助手。', commonConfusion: 'Coze 是建置平台，不等於所有 Agent 概念本身。' }],
    metaphor: 'Coze 像有透明工作台的實驗室：你可以把開始、AI 處理與結束放到桌上，連線後觀察資料怎麼走。',
    technicalExplanation: ['Agent 著重根據目標回應或選擇能力。', 'Workflow 著重節點、連線與可重現流程。', '平台介面只是承載這些概念的一種工具。'],
    diagram: ['你的需求', '選 Agent 或 Workflow', '在 Coze 組合', '測試輸入輸出'],
    caseStudy: { title: 'AI 商業分析助手', label: '模擬案例', description: '第一版只把公司描述轉成「現況、機會、待確認」三段，不連外部資料，也不宣稱是即時分析。' },
    steps: ['先寫下助手的單一目標。', '列出它可使用與不可使用的資料。', '決定先用 Agent 對話，還是用固定 Workflow。'],
    exercise: { prompt: '哪些情境適合先用 Coze 做原型，而不是立刻寫大量程式？', success: ['流程需要快速驗證', '資料與風險邊界清楚', '沒有把原型當正式生產系統'], hint: '原型重點是快速看見流程與輸出。', answer: '需求仍在確認、想快速測試 Prompt 與節點關係，而且資料與權限風險可控時，適合先用 Coze 做原型。' },
    quiz: [question('q11', 'true-false', '只要使用 Coze，就自動擁有正確、即時、已查證的資料。', ['正確', '錯誤'], 1, '平台提供建置能力；資料是否即時與可信仍取決於來源、工具與驗證。', '平台能力與資料真實性分開看。')],
    commonErrors: [{ mistake: '還沒定義目標就開始拖節點', cause: '把點擊當設計', fix: '先寫輸入、期望輸出與邊界' }, { mistake: '照舊截圖找按鈕', cause: '忽略版本差異', fix: '對照目前官方介面與日期' }],
    summary: ['Coze 是組合 AI 應用與 Workflow 的平台。', '先有需求與流程，再操作介面。'], nextLesson: '下一課：建立第一個 Agent', verification: '版本敏感', sourceNote: cozeSource,
  }),
  makeLesson({
    id: 'lesson-12', phase: 2, lessonNumber: 12,
    title: '建立第一個 Agent', subtitle: '用一個清楚角色完成一種任務',
    description: '為 AI 商業分析助手定義角色、輸入、輸出與禁止事項。', objectives: ['寫出可測試的 Agent 目標', '區分 System 與 User 需求', '設計三個測試案例'], prerequisites: ['完成 Coze 是什麼'],
    concepts: [{ term: 'System Prompt', chinese: '系統提示詞', plain: '設定 Agent 長期角色、規則與邊界的指示。', definition: '位於對話規則層、用來規範模型行為和限制的指令。', why: '讓多次輸入仍遵守同一角色與安全邊界。', example: '只使用使用者提供資料；缺少就寫待確認。', commonConfusion: 'System Prompt 不能取代真正的工具權限控制。' }, { term: 'User Prompt', chinese: '使用者提示詞', plain: '這一次要 Agent 處理的具體問題或材料。', definition: '由使用者提供、描述當前任務與內容的訊息。', why: '把長期規則與每次任務分開。', example: '請分析這段公司簡介。' }],
    metaphor: 'System Prompt 像職務說明與公司規範；User Prompt 像今天交辦的工作。',
    technicalExplanation: ['角色只需要一種清楚責任。', '輸出格式要能檢查。', '禁止事項不能只靠文字，未來仍需權限與流程配合。'],
    diagram: ['System：角色與邊界', '+ User：本次材料', 'Agent 回答', '依規則檢查'],
    caseStudy: { title: '商業分析 Agent', label: '模擬案例', description: '輸入模擬公司資料；只整理現況、機會與待確認，不提供投資建議。' },
    steps: ['在目前 Coze 官方介面建立 Agent／Bot 類應用。', '寫入單一角色、三段輸出與「不得補造資料」。', '用正常、缺資料、互相矛盾三種輸入測試。'],
    exercise: { prompt: '寫一段不超過 80 字的 System Prompt。', success: ['角色單一', '輸出格式明確', '未知內容標待確認'], hint: '不要加入尚未需要的工具或十幾條規則。', answer: '你是商業分析助手。只根據使用者提供內容，輸出現況、可能機會、待確認三段；不得補造公司、數字或來源。' },
    quiz: [question('q12', 'single', '哪一項較適合放在 System Prompt？', ['這次公司的營收資料', '長期遵守的角色、格式與禁止事項', '使用者今天貼的新聞全文'], 1, 'System Prompt 用於長期規則；本次材料放在 User Prompt。', '分清職務說明與今天的工作單。')],
    commonErrors: [{ mistake: '角色過多', cause: '想一次做研究、財務、法律與行銷', fix: '先做單一任務 Agent' }, { mistake: '只測成功案例', cause: '沒有驗證邊界', fix: '加入缺資料與衝突輸入' }],
    summary: ['System Prompt 管長期規則；User Prompt 管本次任務。', '先讓一種任務可測，再擴充。'], nextLesson: '下一課：建立第一個 Workflow', verification: '版本敏感', sourceNote: cozeSource,
  }),
  makeLesson({
    id: 'lesson-13', phase: 2, lessonNumber: 13,
    title: '建立第一個 Workflow', subtitle: '把輸入、AI 處理與輸出放在一條線上',
    description: '建立 Start → LLM → End 的最小流程，先看懂資料流。', objectives: ['辨認三個必要節點', '說出連線代表資料流', '用最小流程測試輸入輸出'], prerequisites: ['完成第一個 Agent', '理解 Workflow'],
    concepts: [{ term: 'Node', chinese: '節點', plain: 'Workflow 裡負責一件工作的方塊。', definition: '接收輸入、執行特定處理並產生輸出的流程單元。', why: '把複雜工作拆成可觀察與可除錯的小步驟。', example: 'Start、LLM、End 各是一個節點。', commonConfusion: '節點不是裝飾；每個節點都要有清楚輸入與輸出。' }, { term: 'Edge', chinese: '連線／邊', plain: '把一個節點的結果送到下一個節點。', definition: '描述節點執行順序與資料傳遞關係的連接。', why: '讓資料知道下一站去哪裡。', example: 'Start 的 company_description 連到 LLM。' }],
    metaphor: 'Workflow 像透明輸送線：每一站只完成一項工作，連線把材料送到下一站。',
    technicalExplanation: ['Start 定義流程收到的資料。', 'LLM 根據 Prompt 處理資料。', 'End 定義要交付的結果。', '先保持三節點，確認資料真的走通。'],
    diagram: ['Start', 'company_description', 'LLM', 'analysis', 'End'],
    caseStudy: { title: '最小商業分析 Workflow', label: '模擬案例', description: '輸入一段公司描述，輸出三段整理；不查外部網站。' },
    steps: ['在目前官方介面建立 Workflow。', '保留或加入 Start、LLM、End。', '用連線把輸入傳給 LLM，再把結果傳給 End。', '執行一次正常測試並保存輸入輸出。'],
    exercise: { prompt: '畫出最小 Workflow，並在每條連線上寫資料名稱。', success: ['三節點順序正確', '至少一個輸入與一個輸出', '連線有資料名稱'], hint: '不要先加 Condition、Plugin 或 Code。', answer: 'Start（company_description）→ LLM（analysis）→ End（analysis）。' },
    quiz: [question('q13', 'single', '第一次建立 Workflow，最重要的是？', ['先加入十個節點', '先讓 Start → LLM → End 的資料流跑通', '先設計複雜迴圈'], 1, '最小流程能先驗證輸入、處理與輸出，降低除錯難度。', '先證明最短路徑。')],
    commonErrors: [{ mistake: '一次加入太多節點', cause: '想直接完成最終系統', fix: '先跑通三節點最小流程' }, { mistake: '只連線但沒映射資料', cause: '把線當裝飾', fix: '檢查每個節點輸入值來自哪裡' }],
    summary: ['Node 完成一項工作；Edge 傳遞順序與資料。', '先跑通最小流程再增加功能。'], nextLesson: '下一課：Start Node', verification: '版本敏感', sourceNote: cozeSource,
  }),
  makeLesson({
    id: 'lesson-14', phase: 2, lessonNumber: 14,
    title: 'Start Node', subtitle: '先定義流程需要收到什麼',
    description: '用清楚的變數名稱、類型與必填規則建立可靠入口。', objectives: ['解釋 Start Node 的角色', '設計一個文字輸入', '辨認空輸入與格式問題'], prerequisites: ['完成最小 Workflow'],
    concepts: [{ term: 'Start Node', chinese: '開始節點', plain: 'Workflow 的入口，定義外面要交給流程哪些資料。', definition: '宣告工作流輸入欄位並啟動執行的起始節點。', why: '輸入不清楚，後面每一個節點都可能拿錯資料。', example: 'company_description：公司描述文字。', commonConfusion: 'Start 只定義入口，不負責分析內容。' }, { term: 'Variable', chinese: '變數', plain: '用一個名字暫時保存流程中的資料。', definition: '在流程中以名稱參照的資料值，其型別和內容可在執行時改變。', why: '讓節點可以明確傳遞同一份資料。', example: 'company_description =「這是一家……」' }],
    metaphor: 'Start Node 像收件櫃台：先規定要填公司名稱、需求與聯絡方式，後面部門才不會拿到缺欄資料。',
    technicalExplanation: ['變數名稱要能看懂用途。', '文字輸入與布林值等類型不同。', '必要欄位缺失時應停止並提示，而不是讓模型猜。'],
    diagram: ['外部輸入', 'Start 驗證欄位', 'company_description', '送往下一節點'],
    caseStudy: { title: '公司描述輸入', label: '模擬案例', description: 'MVP 只需要 company_description 一個文字欄位，避免一開始建過多變數。' },
    steps: ['在 Start 建立文字變數 company_description。', '寫清楚欄位說明與示例。', '分別測試正常文字與空白輸入。'],
    exercise: { prompt: '為商業分析 Workflow 設計最少的 Start 輸入。', success: ['一個清楚變數名', '類型正確', '有空輸入處理'], hint: '這一版不需要公司所有資料。', answer: '使用文字變數 company_description，設為必要；空白時回傳「請先提供公司描述」。' },
    quiz: [question('q14', 'true-false', '變數名稱用 a、b、c 比 company_description 更適合初學者。', ['正確', '錯誤'], 1, '清楚名稱讓資料流更容易閱讀與除錯。', '名字能否讓你一眼知道內容？')],
    commonErrors: [{ mistake: '變數名稱看不懂', cause: '只求簡短', fix: '用用途命名，如 company_description' }, { mistake: '沒有測空輸入', cause: '只測正常資料', fix: '加入必要欄位與清楚錯誤訊息' }],
    summary: ['Start Node 定義入口。', '變數名稱、類型與空值處理是後續穩定的基礎。'], nextLesson: '下一課：LLM Node', verification: '版本敏感', sourceNote: cozeSource,
  }),
  makeLesson({
    id: 'lesson-15', phase: 2, lessonNumber: 15,
    title: 'LLM Node', subtitle: '把輸入變數放進可檢查的 Prompt',
    description: '設定模型處理任務、引用 Start 變數，並用三種輸入測試。', objectives: ['說出 LLM Node 的輸入與輸出', '正確引用上游變數', '用測試找出 Prompt 漏洞'], prerequisites: ['完成 Start Node', '理解 Prompt'],
    concepts: [{ term: 'LLM Node', chinese: '大型語言模型節點', plain: 'Workflow 裡呼叫模型處理文字的一站。', definition: '接收上游變數、套用 Prompt 與模型設定並產生結果的節點。', why: '把需要理解或生成文字的工作放在明確步驟中。', example: '把 company_description 整理成三段分析。', commonConfusion: 'LLM Node 不會自動知道 Start 裡的變數，必須正確引用或映射。' }],
    metaphor: 'LLM Node 像分析部門：收件櫃台必須把正確資料送進來，部門也要有清楚工作規則。',
    technicalExplanation: ['輸入來自 Start 的變數。', 'Prompt 定義處理方式與輸出格式。', '模型產生 analysis 結果。', '缺資料、矛盾資料與提示注入都需要測試。'],
    diagram: ['company_description', 'LLM Prompt', '模型處理', 'analysis'],
    caseStudy: { title: '三段式分析', label: '模擬案例', description: 'Prompt 要求只依輸入，輸出已知現況、可能機會、待確認；不可生成真實營收或市場份額。' },
    steps: ['在 LLM Node 引用 company_description。', '寫入三段輸出與不得補造的限制。', '命名輸出 analysis。', '測正常、缺資料、互相矛盾三種輸入。'],
    exercise: { prompt: '資料不足時，LLM Node 應如何輸出？', success: ['明示資料不足', '列出需要補什麼', '不自行猜測'], hint: '「完整」不是比「真實」更重要。', answer: '在「待確認」列出缺少的產品、客戶或數字，說明目前無法下結論，不自行補造。' },
    quiz: [question('q15', 'single', 'LLM Node 沒收到 Start 的內容，第一個該檢查什麼？', ['換更貴模型', '上游變數映射與 Prompt 引用', '加入更多形容詞'], 1, '先確認資料是否真的進入節點，再調整模型或 Prompt。', '先看 Input，而不是猜模型。')],
    commonErrors: [{ mistake: 'Prompt 沒引用變數', cause: '只寫了任務句子', fix: '檢查輸入映射與變數插入' }, { mistake: '資料不足仍強迫完整分析', cause: '沒有未知處理', fix: '加入待確認與停止條件' }],
    debugSteps: ['打開 LLM Node 的執行紀錄。', '確認 Input 中真的有 company_description。', '確認 Prompt 引用了正確變數。', '查看 Output 與錯誤訊息，只改一項再測。'],
    summary: ['LLM Node 需要正確上游輸入與明確 Prompt。', '先檢查資料流，再調模型。'], nextLesson: '下一課：End Node 與完整測試', verification: '版本敏感', sourceNote: cozeSource,
  }),
  makeLesson({
    id: 'lesson-16', phase: 2, lessonNumber: 16,
    title: 'End Node 與完整測試', subtitle: '把真正需要的結果交付出去',
    description: '設定輸出欄位，完成端到端測試與最小 Debug Lab。', objectives: ['解釋 End Node 的角色', '映射 LLM 輸出', '完成正常、空白與衝突三種測試'], prerequisites: ['完成 LLM Node'],
    concepts: [{ term: 'End Node', chinese: '結束節點', plain: 'Workflow 的出口，指定最後要交付哪些資料。', definition: '接收上游結果並定義工作流對外輸出欄位的終止節點。', why: '讓呼叫者拿到穩定、清楚、可使用的結果。', example: '輸出 analysis，而不是整份內部執行紀錄。', commonConfusion: 'End 不負責修正 LLM 內容；它負責選擇與交付結果。' }, { term: 'Run Log', chinese: '執行紀錄', plain: '每一次測試中，各節點收到與產生什麼的記錄。', definition: '工作流執行時的節點輸入、輸出、狀態與錯誤資訊。', why: '讓除錯回到證據，而不是猜測。', example: 'Start 有值，但 LLM Input 是空白。' }],
    metaphor: 'End Node 像出貨檢查站：只把客戶需要的成品交付；Run Log 則像生產履歷，能追查是哪一站出了問題。',
    technicalExplanation: ['把 LLM 的 analysis 映射到 End。', '執行正常輸入並比對格式。', '再測空白與衝突資料。', '發現錯誤時沿 Start → LLM → End 查 Input / Output。'],
    diagram: ['Start：輸入', 'LLM：analysis', 'End：analysis', '使用者收到結果'],
    caseStudy: { title: '第一個完整 Workflow', label: '模擬案例', description: '完成 Start → LLM → End；輸出只包含三段分析與待確認，不連外部即時資料。' },
    steps: ['在 End 建立 analysis 輸出。', '映射 LLM Node 的 analysis。', '跑三組測試並保存 Run Log。', '用自己的話解釋每個節點。'],
    exercise: { prompt: 'Run Log 顯示 Start 有輸入、LLM 有輸出，但 End 是空白。你先查什麼？', success: ['指出 End 映射', '不先怪模型', '一次只改一項'], hint: '錯誤發生在有輸出的 LLM 之後。', answer: '先檢查 End 的 analysis 是否映射到 LLM 的正確輸出欄位；修正後用同一輸入重跑。' },
    quiz: [question('q16', 'scenario', '最可靠的 Debug 順序是？', ['一直重跑直到成功', '看錯誤 → 找節點 → 查 Input → 查 Output → 查變數 → 修改一項再測', '把所有節點一起刪掉'], 1, '逐站用執行證據定位第一個異常點，能避免盲目修改。', '沿著資料流查第一個不符合預期的地方。')],
    commonErrors: [{ mistake: 'End 映射到錯欄位', cause: '輸出名稱相似', fix: '從 Run Log 核對節點與欄位' }, { mistake: '完成一次正常測試就結束', cause: '忽略邊界情境', fix: '至少測正常、空白、衝突' }],
    debugSteps: ['看完整錯誤訊息。', '找第一個失敗或資料異常的 Node。', '依序比較該 Node 的 Input、Output 與 Variable。', '只修改一項後，用同一筆資料重測。', '記錄原因與修復結果。'],
    summary: ['End Node 定義穩定輸出。', 'Run Log 是 Workflow 除錯的主要證據。', 'MVP 第一個專案完成：Start → LLM → End。'], nextLesson: '下一課：Hermes Agent 是什麼', verification: '版本敏感', sourceNote: cozeSource,
  }),
]
